# Generated by Django 3.0.2 on 2020-02-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200204_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='FIELDNAME',
            new_name='image',
        ),
    ]
